**step-1**

**creare a dataframe**

- we will create a datframe using list
- we will ctreate a datframe using dictionary

In [2]:
import pandas as pd


In [3]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [4]:
type(d1)

pandas.core.frame.DataFrame

**step-2**

**provide the data**

In [5]:
names=['vishwas','sathish','bhanu']
pd.DataFrame(names)

0
0  vishwas
1  sathish
2    bhanu

In [6]:
names=['vishwas','sathish','bhanu']
age=[23,23,22]
data=zip(names,age)
pd.DataFrame(data)

0   1
0  vishwas  23
1  sathish  23
2    bhanu  22

In [7]:
names=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']
pd.DataFrame(zip(names,age,city))

0   1     2
0  vishwas  23   hyd
1  sathish  23  ecil
2    bhanu  22   blr

**step-3**
**provide the column names**

In [8]:
names=['vishwas','sathish','bhanu']
pd.DataFrame(names,
             columns=['names'])

names
0  vishwas
1  sathish
2    bhanu

In [9]:
names=['vishwas','sathish','bhanu']
age=[23,23,22]
pd.DataFrame(zip(names,age),
             columns=['names','age'])

names  age
0  vishwas   23
1  sathish   23
2    bhanu   22

In [10]:
names=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)

cols=['names','age','city']

pd.DataFrame(data,columns=cols)

names  age  city
0  vishwas   23   hyd
1  sathish   23  ecil
2    bhanu   22   blr

**step-4**

**providing index**

In [11]:
names=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)
ix=['a','b','c']
cols=['names','age','city']

pd.DataFrame(data,
             index=ix,
             columns=cols)


names  age  city
a  vishwas   23   hyd
b  sathish   23  ecil
c    bhanu   22   blr

In [12]:
names=['vishwas','sathish','bhanu']
pd.DataFrame(names)

names=['vishwas','sathish','bhanu']
pd.DataFrame(names,
             columns=['names'])

names
0  vishwas
1  sathish
2    bhanu

In [13]:
names=['vishwas','sathish','bhanu']
pd.DataFrame(names)

names=['vishwas','sathish','bhanu']
pd.DataFrame(names,
             columns=['names'])

names=['vishwas','sathish','bhanu']
age=[23,23,22]
pd.DataFrame(zip(names,age),
            columns=['names','age'])


names=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']

data=zip(names,age,city)

cols=['names','age','city']

pd.DataFrame(data,columns=cols)

names  age  city
0  vishwas   23   hyd
1  sathish   23  ecil
2    bhanu   22   blr

In [14]:
name=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']
data=zip(name,age,)
column=['names','age',]
df=pd.DataFrame(data, index=city, columns=column)

In [16]:
df


names  age
hyd   vishwas   23
ecil  sathish   23
blr     bhanu   22

- create a dataframe
- provide the data
- add the columns
- provide thr column name
- provide the index

In [17]:
import pandas as pd


In [18]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

**step-5**
**add a new column on existing data frame**

In [19]:
# craeate a dataframe
# name 
# age
# city

import pandas as pd
name=['vishwas','sathish','bhanu']
age=[23,23,22]
city=['hyd','ecil','blr']

data=zip(name,age,city)

column=['names','age','city']

df=pd.DataFrame(data, index=city, columns=column)
df

names  age  city
hyd   vishwas   23   hyd
ecil  sathish   23  ecil
blr     bhanu   22   blr

- if you want to add a new column 
- first check how many rows are there
- for examle in above dataframe we have 3 rows
- your new column also should have 3 rows 
- suppose inwanr to create a new column:salary
- make a list with 3 values
- salary=[100000,200000,300000]

$syntax$:dataframe[column]=list of values
- salary=[100000,200000,300000]
- df['salary']=salary

In [20]:
df['salary']=[]

ValueError: Length of values (0) does not match length of index (3)

In [21]:
salary=[100000,200000,300000]
df['salary']=salary
df

names  age  city  salary
hyd   vishwas   23   hyd  100000
ecil  sathish   23  ecil  200000
blr     bhanu   22   blr  300000

**use case-1**

- craete empty data frame first 
- create 3 list using listb comprehension 
- list1=a values from 1 to 10
- list2=square of 1 to 10
- list3=cube of 1 to 10
- finally make a dataframe


In [23]:
import pandas as pd
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [24]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df1['x']=l1
df1['y']=l2
df1['z']=l3
df1

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**step-6**

**update the already existed colum**

- creatw a newv column
   - creating a new list salary=[1000,2000,3000]
   -df['s']
   -creating a new column the column name is our choice 
-update existing column are same way only
  - heere also we need a make a list of values= number of rows
  - while updating the existing column
  - we need to provide already existed column name only
  - df['z']= list of values

In [25]:
# dataframe name: df1
# list of values varaiable name: z
# which column we want to update : z'

z=[i**4 for i in range(1,10)]
df1['z']=z
df1

x   y     z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [26]:
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['number']=l1
df2['square']=l2
df2['cube']=l3

df2

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**step-7**

**drop the column**

In [27]:
# how to check the columns
df1.columns

Index(['x', 'y', 'z'], dtype='object')

- if you want to drop a specific column 
- we will use drop method
- we already know about difference between keyword and method
- keyword will use directly
- methods will use with corresponding dataframe
- **method name:drop**

**df1.drop()**

- column which column you want to drop
- axis:represents the specified value is a row or column
   - axis=0 means rows
   - axis=1 means column
   - by default axis=0
- inplace:will provide overwrite the dataframe or not

   - inplace= True,this indicates overwrite the dataframe
     
   - inplace=False,this indicates the modified dataframe will be use when you
     provide new variables for the operation

In [28]:
df1.drop('x')
# we are not providing axis
# it assuming the providing value is a row
# by default axis=0 =====rows

KeyError: "['x'] not found in axis"

In [77]:
df1.drop('x',axis=1)

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [78]:
df1.drop('x',axis=1,inplace=True)
df1

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [ ]:
# read the data frame 
# provide the data 
# provide the column names
# chande the index 
# add the new column
# modify the existing column
# drop the column
#   axis  inplace
# you need to create a new column
# drop the old column

**step-8**

**drop the row**

- drop the column and drop tyhe rows both are similar only
- the only difference is axis
   - axis= 0 represents rows
   -  by default axis=0available
   -  which means if we provide any value ,it will represents rows only

In [35]:
#dataframe name: df1
import pandas as pd 
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['number']=l1
df2['square']=l2
df2['cube']=l3

df2


number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [36]:
df2.drop(4)
# if we run this we will get error
# by default axis=0 which represents about rows 
# but 'number is a column 
# if you wantto drop row ,the provide tyhe row index


number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [39]:
# multiplerow 
# multiple column keep always in a list
df2.drop([4,8])

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [43]:
df2.columns[[0,1]]

Index(['number', 'square'], dtype='object')

In [29]:
df2.drop([0,1],axis=1)
#[0,1] index
# axis=1 column
# error

KeyError: '[0, 1] not found in axis'

**step9**

**how to select the column**`

In [45]:
df2['square']

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: square, dtype: int64

In [48]:
df2[['square']]

square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [50]:
type(df2['number'])

pandas.core.series.Series

In [51]:
type(df2[['number']])

pandas.core.frame.DataFrame

In [53]:
df2.number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: number, dtype: int64

- df2['number ']:series type 
- df2[['number' ]]:dataframe type
- df2.number:series type

In [56]:
cols=['number','square']
df2[cols]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [57]:
df2['number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values comes in an array
- array means it is a list of elements only re4presents usimg numpy package 
- generally elements present in 4 way 
   - list: basic representation 
   - numpy array : array with numpy package
   - tensors : tensorflow package
   - torch :pytorch package

In [2]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [3]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [ ]:
#tensor([1,2,3,4})


In [4]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [5]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [58]:
df2['number'].values
# imagine we  worked on an ml problem 
# we got some series of values also we can create a dataframe


array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [68]:
df2['Number']=df2['number'].values
df2

number  square  cube  Number
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

**step-10**

**save the data frame**

- data frame we can save in teo formats

   - csv : commsa seoerated value 
   - xlsx : excel format

- in order to save anyn data 

   - where you want to save : directory name

   - what is the name of the file for storing 
   - what is the extension
- we already seen same in file handling session


In [ ]:
#case-1:saving file at same location wher this python file
# import as
# os.getcwd()
# no need to provide directory path
# directly give only name of the file
# and extension

In [70]:
# dataframe name: df2
df2.to_csv('datal.csv')
df2.to_excel('datal.xlsx')

**step-11**
 **how to read a dataframe**

In [71]:
import pandas as pd 
pd.read_csv('datal.csv')

Unnamed: 0  number  square  cube  Number
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

In [66]:
import os 
os.getcwd()

'C:\\Users\\admin\\OneDrive'

In [72]:
import pandas as pd 
pd.read_excel('datal.xlsx')

Unnamed: 0  number  square  cube  Number
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

**step-12**

**how to avoid index column**

- while we save the dataframe
- automatically a new column will create 
- that we need to avoid
- permission denied means close the data file from laptop

    

In [73]:
# dataframe name: df2
# save the data with out index column
df2.to_csv('datal.csv',index=False)
df2.to_excel('datal.xlsx',index=False)

In [74]:
# read the data 
import pandas as pd
pd.read_csv('datal.csv')

number  square  cube  Number
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9